version: "3.9"

networks:
  prod_internal:
    driver: bridge
    internal: true   # NO external access
  prod_public:
    driver: bridge

services:
  frontend:
    image: frontend-prod
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    ports:
      - "127.0.0.1:${FRONTEND_PORT}:8080"
    depends_on:
      - backend
    networks:
      - prod_internal
      - prod_public

  backend:
    image: backend-prod
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: prod
    ports:
      - "127.0.0.1:${BACKEND_PORT}:3000"
    environment:
      NODE_ENV: production
      DB_HOST: database
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      DB_DATABASE: ${MYSQL_DATABASE}
    depends_on:
      database:
        condition: service_healthy
    networks:
      - prod_internal

  database:
    image: mysql:8.4
    container_name: mysql-prod
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data_prod:/var/lib/mysql
    networks:
      - prod_internal
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]

  migrate:
    image: backend-prod
    command: npm run migrate
    build:
      target: prod
      context: ./backend
      dockerfile: Dockerfile

    depends_on:
      database:
        condition: service_healthy
    environment:
      NODE_ENV: production
      DB_HOST: database
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      DB_DATABASE: ${MYSQL_DATABASE}
    restart: "no"
    profiles: [ "tools" ]
    networks:
      - prod_internal

volumes:
  mysql_data_prod:
