version: "3.9"

services:
  frontend:
    image: frontend-dev
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    ports:
      - "127.0.0.1:${FRONTEND_PORT}:4200"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      CHOKIDAR_USEPOLLING: "true"
    depends_on:
      - backend

  backend:
    image: backend-dev
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: dev
    ports:
      - "127.0.0.1:${BACKEND_PORT}:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
      DB_HOST: database
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      DB_DATABASE: ${MYSQL_DATABASE}
      PORT: ${PORT}
      HOST: ${HOST}
    depends_on:
      database:
        condition: service_healthy

  database:
    image: mysql:8.4
    container_name: mysql-dev
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data_dev:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]

  migrate:
    image: backend-dev
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: dev
    command: npm run migrate
    depends_on:
      database:
        condition: service_healthy
    environment:
      NODE_ENV: development
      DB_HOST: database
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      DB_DATABASE: ${MYSQL_DATABASE}
    restart: "no"

  seed:
    image: backend-dev
    command: npm run seed
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: dev
    depends_on:
      migrate:
        condition: service_completed_successfully
      database:
        condition: service_healthy
    environment:
      NODE_ENV: development
      DB_HOST: database
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      DB_DATABASE: ${MYSQL_DATABASE}
    restart: "no"

volumes:
  mysql_data_dev:
